### PR TITLE
Webpacked the extension

### PR DESCRIPTION
**Pull request by usernamehw**
I thought that this extension had a lot of files, but it were just `.gif` files inside, but it was too late to stop, so here we are.

Reduces the size of the extension and the number of files.

Removed `copy-paste` dependency and used `vscode.env.clipboard.writeText()` instead.

### CODE REVIEW

**Review by ryanraposo — APPROVED** [review]
Looks great

**Comment by usernamehw** [comment]
Is it even working? The copy button and the file paths?

**Comment by ryanraposo** [comment]
I still need to test this and the webpack, but I assumed you tried it out. Didn't know about vscode.env.clipboard.writeText(), nice to drop a dependency if those methods work out.

**Comment by ryanraposo** [comment]
@usernamehw I need to set up the workflow again and get reacquainted, forgive me for some hiccups moving forward.

**Comment by usernamehw** [comment]
No worries.

**Comment by ryanraposo** [comment]
@usernamehw I'm having trouble debugging since the webpack, any ideas?

**Comment by usernamehw** [comment]
Damn... The `"preLaunchTask"` in **launch.json** never worked for me. Does the debugging work if you run `npm run watch` in terminal and delete `"preLaunchTask"`. If that's not working or not good enough, you can revert the change.

**Comment by ryanraposo** [comment]
> Damn... The `"preLaunchTask"` in **launch.json** never worked for me. Does the debugging work if you run `npm run watch` in terminal and delete `"preLaunchTask"`. If that's not working or not good enough, you can revert the change.

Yeah no luck, gunna revert.

**Pull request merged**
